@startuml

class VoiceReceiverSet {
    - Set<VoiceReceiver> receivers

    + Set<VoiceReceiver> getReceivers()
    + void addReceiver(VoiceReceiver)
    + void removeReceiver(VoiceReceiver)
}

class VoiceReceiverCreator {
    + VoiceReceiver createReceiver()
}

class VoiceReceiver {
    - {static} int PACKET_SIZE

    - VoicePlayer player
    - int serverPort
    - byte[] buffer
    - DatagramSocket socket
    - DatagramPacket packet

    + VoiceReceiver()
    + void start()
    + void run()
    + void end()
}

class VoicePlayer{
    - {static} int HZ
    - {static} int BITS
    - {static} int MONO

    - SourceDataLine source
    - byte[] voice

    + VoicePlayer()
    + void start()
    + void run()
    + void setVoice(byte[])
    + void end()
}

class VoiceSenderSet {
    - Set<VoiceSender> senders

    + Set<VoiceSender> getSenders()
    + void addSender(VoiceSender)
    + void removeSender(VoiceSender)
}

class VoiceSenderCreator {
    + VoiceSender createSender()
}

class VoiceSender {
    - {static} int SERVER_HOST
    - {static} int SERVER_PORT
    - {static} int INTERVAL

    - VoiceListener listener
    - InetSocketAddress address
    - DatagramSocket socket

    + VoiceSender()
    + void start()
    + void run()
    + void end()
}

class VoiceListener {
    - {static} int HZ
    - {static} int BITS
    - {static} int MONO

    - TargetDataLine target
    - AudioInputStream stream
    - byte[] voice

    + VoiceListener()
    + void start()
    + void run()
    + byte[] getVoice()
    + void end()
}

class Thread {
     + void start()
     + void run()
}


VoiceReceiverSet o-- VoiceReceiver
VoiceReceiverCreator --> VoiceReceiver
VoiceReceiver --|> Thread
VoiceReceiver *-- VoicePlayer
VoicePlayer --|> Thread

VoiceSenderSet o-- VoiceSender
VoiceSenderCreator --> VoiceSender
VoiceSender --|> Thread
VoiceSender *-- VoiceListener
VoiceListener --|> Thread

@enduml